workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.anonymous.Sensor_alarm"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install
          
  
      - name: Build Android release
        script: | 
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sathvik.malgikar@gmail.com
        notify:
          success: true
          failure: false
      


  